import {adjectives,criminals,motives,nouns,weapons} from '@/lib/data/cards';import type{Category,GameRoom,HintTile,TeamState}from '@/lib/types/game';
function sample<T>(items:T[],count:number):T[]{const copy=[...items],result:T[]=[];while(result.length<count&&copy.length){const i=Math.floor(Math.random()*copy.length);result.push(copy.splice(i,1)[0])}return result}function pick<T>(items:T[]):T{return items[Math.floor(Math.random()*items.length)]}function tile(word:string,type:'adjective'|'noun'):HintTile{return{id:`${type}-${word}`,word,type}}
export function createRoom():GameRoom{const cc=sample(criminals,9),cw=sample(weapons,9);const code=Math.random().toString(36).slice(2,8).toUpperCase();return{code,globalRound:1,candidates:{criminals:cc,weapons:cw,motives},answer:{criminal:pick(cc),weapon:pick(cw),motive:pick(motives)},openTiles:[...sample(adjectives,6).map(w=>tile(w,'adjective')),...sample(nouns,6).map(w=>tile(w,'noun'))],hints:{criminal:[],weapon:[],motive:[]},teams:{},createdAt:Date.now()}}
export function createTeam(name:string,round:number):TeamState{return{name,round,status:'thinking',guessTiles:[true,true,true,true],excluded:{criminals:[],weapons:[],motives:[]},selected:[]}}
export function categoryOf(room:GameRoom,card:string):Category{if(room.candidates.criminals.includes(card))return'criminals';if(room.candidates.weapons.includes(card))return'weapons';return'motives'}
export function addRoundTiles(room:GameRoom):GameRoom{const words=room.openTiles.map(t=>t.word);const adj=adjectives.filter(w=>!words.includes(w));const nn=nouns.filter(w=>!words.includes(w));const extra:HintTile[]=[];if(adj.length)extra.push(tile(pick(adj),'adjective'));if(nn.length)extra.push(tile(pick(nn),'noun'));return{...room,openTiles:[...room.openTiles,...extra]}}
export function resolveExclude(room:GameRoom,team:TeamState):TeamState{if(!team.pending||team.pending.type!=='exclude')return team;const ans=[room.answer.criminal,room.answer.weapon,room.answer.motive];const failed=team.pending.cards.some(c=>ans.includes(c));if(failed){const gt=[...team.guessTiles];const i=gt.findIndex(Boolean);if(i>=0)gt[i]=false;const alive=gt.some(Boolean);return{...team,status:alive?'retry':'game-over',guessTiles:gt,selected:[],pending:undefined,notice:alive?`제외 실패: ROUND ${team.round} 재도전`:'GAME OVER: 추리 타일을 모두 사용했습니다.'}}const excluded=structuredClone(team.excluded);for(const card of team.pending.cards){const cat=categoryOf(room,card);if(!excluded[cat].includes(card))excluded[cat].push(card)}return{...team,status:'round-complete',excluded,selected:[],pending:undefined,notice:`제외 성공: ROUND ${team.round} 완료`}}
export function resolveFinal(room:GameRoom,team:TeamState):TeamState{if(!team.pending||team.pending.type!=='final')return team;const ok=team.pending.criminal===room.answer.criminal&&team.pending.weapon===room.answer.weapon&&team.pending.motive===room.answer.motive;if(ok)return{...team,status:'success',pending:undefined,notice:'최종 추리 성공! 사건을 해결했습니다.'};const gt=[...team.guessTiles];const i=gt.findIndex(Boolean);if(i>=0)gt[i]=false;const alive=gt.some(Boolean);return{...team,status:alive?'thinking':'game-over',guessTiles:gt,pending:undefined,notice:alive?'최종 추리 실패: 다시 시도할 수 있습니다.':'GAME OVER: 남은 추리 타일이 없습니다.'}}
export function canStartNextRound(room:GameRoom):boolean{const teams=Object.values(room.teams);const active=teams.filter(t=>t.status!=='game-over');return active.length>0&&active.every(t=>t.status==='round-complete'||t.status==='success')}
